version: "3.2"

services:
  python:
    container_name: fractal-container
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    volumes:
      - type: bind
        source: "./"
        target: "/root/generate_fractal/"
